spring:
  application:
    name: server-transformer

  datasource:
    url: jdbc:postgresql://db.tpzemlslqgawxqsbvpqz.supabase.co:5432/postgres?user=postgres&password=3103Kirushanth
    username: postgres
    password: 3103Kirushanth
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    url: jdbc:postgresql://db.tpzemlslqgawxqsbvpqz.supabase.co:5432/postgres?user=postgres&password=3103Kirushanth
    username: postgres
    password: 3103Kirushanth
    locations: classpath:db/migration
    baseline-on-migrate: true

supabase:
  s3:
    endpoint: https://tpzemlslqgawxqsbvpqz.storage.supabase.co/storage/v1/s3
    region: us-east-1
    access-key: ${SUPABASE_ACCESS_KEY}
    secret-key: ${SUPABASE_SECRET_KEY}
    bucket: image-bucket



# Thermal Analysis Configuration
thermal:
  analysis:
    api:
      url: http://localhost:8000  # FastAPI service URL
      timeout: 300000             # 5 minutes timeout
      retry:
        max-attempts: 3
        delay: 1000              # 1 second delay between retries
    processing:
      default-sensitivity: 50
      default-image-size: 640
      max-concurrent-analyses: 5


#cloud:
#    aws:
#        region:
#          static: ap-southeast-1
#        credentials:
#          access-key: ${AWS_ACCESS_KEY}
#          secret-key: ${AWS_SECRET_KEY}
#
#aws:
#    bucket:
#        name: power-grid