spring:
  application:
    name: server-transformer

  datasource:
    url: jdbc:postgresql://crossover.proxy.rlwy.net:40950/${PSQL_DATABASE}
    username: ${PSQL_USER}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true