spring:
  application:
    name: server-transformer

  datasource:
    url: jdbc:postgresql://localhost:5432/transformer_db?user=postgres&password=pri-postgres
    username: postgres
    password: pri-postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or 'validate' if schema already created
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/transformer_db?user=postgres&password=pri-postgres
    username: postgres
    password: pri-postgres
    locations: classpath:db/migration
    baseline-on-migrate: true

supabase:
  storage:
    url: https://tpzemlslqgawxqsbvpqz.supabase.co/storage/v1
  service:
    key: ${SUPABASE_SERVICE_KEY}
  s3:
    bucket: image-bucket

# Thermal Analysis Configuration
thermal:
  analysis:
    api:
      url: http://localhost:8000  # FastAPI service URL
      timeout: 300000             # 5 minutes timeout
      retry:
        max-attempts: 3
        delay: 1000              # 1 second delay between retries
    processing:
      default-sensitivity: 50
      default-image-size: 640
      max-concurrent-analyses: 5
